GET http://localhost:3001/users

###

GET http://localhost:3001/games

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "authTest@gmail.com",
    "password": "password123"
}

###

GET http://localhost:3001/users/64eec5df98efa9d9d0ca3bdb/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF1dGhUZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY5MzUyNTA1OX0.0IRNDAgjSHqIpdWQOQtsj25VrDKUagelev5NIare2Pw

###

PATCH http://localhost:3001/users/64eec5df98efa9d9d0ca3bdb
Content-Type: application/json

{
    "gameId": "64f02339d5b5a5b5af3d404e"
}

###

POST http://localhost:3001/
Content-Type: application/json

{
    "email": "authUser@gmail.com",
    "password": "authPassword1"
}

###

POST http://localhost:3001/
Content-Type: application/json

{
    "email": "secondUser@gmail.com",
    "password": "secondPassword2"
}

###

POST http://localhost:3001/users/
Content-Type: application/json

{
    "email": "fourthUser@gmail.com",
    "password": "fourthPassword4"
}

###
POST http://localhost:3001/games/
Content-Type: application/json

{
    "score": 2
}

###
http://localhost:3001/users/64eed241d4850e210be16ae1